#!/usr/bin/env bash
# Fail if the built guide contains a broken internal link.
# Run from the repo root, after `mdbook build docs/guide`.
#
# This exists because mdBook does not validate markdown links. A link to a file
# that is not a book page builds with zero warnings and publishes as a 404 --
# which is how three dead links reached the published site (#92). The ADR and
# reference-doc ingests rewrite links that leave the book, and this is the check
# that keeps them honest.
#
# External (http/https) links are not fetched: that would make the docs build
# depend on third-party availability. Only in-book targets are resolved, against
# the files mdBook actually produced.
set -uo pipefail

BOOK="${1:-docs/guide/book}"
SELF_BLOB="https://github.com/caliban-ai/caliban-operator/blob/main"
SELF_TREE="https://github.com/caliban-ai/caliban-operator/tree/main"

if [[ ! -d "$BOOK" ]]; then
  echo "error: $BOOK not found (run 'mdbook build docs/guide' first)" >&2
  exit 1
fi

broken=0
checked=0

while IFS= read -r page; do
  rel="${page#"$BOOK"/}"
  dir="$(dirname "$rel")"
  [[ "$dir" == "." ]] && dir=""

  while IFS= read -r href; do
    # A link the ingests rewrote to point back at this repository names a path
    # that must exist here. Resolve it against the working tree rather than
    # fetching it -- a rewrite aimed at a path that does not exist publishes as
    # a link out to a 404, which is how the ADR 0000 bootstrap reference stayed
    # broken through its first "fix".
    case "$href" in
      "$SELF_BLOB"/*|"$SELF_TREE"/*)
        path="${href#"$SELF_BLOB"/}"
        path="${path#"$SELF_TREE"/}"
        path="${path%%#*}"
        path="${path%/}"
        checked=$((checked + 1))
        if [[ -n "$path" && ! -e "$path" ]]; then
          echo "broken: $rel -> $href (no such path in this repo: $path)"
          broken=$((broken + 1))
        fi
        continue
        ;;
    esac

    case "$href" in
      http*|//*|'#'*|mailto:*|'') continue ;;
    esac

    target="${href%%#*}"
    [[ -z "$target" ]] && continue

    case "$target" in
      /*) resolved="$BOOK$target" ;;
      *)  resolved="$BOOK/${dir:+$dir/}$target" ;;
    esac

    # Collapse `./` and `segment/../`.
    resolved="$(printf '%s' "$resolved" | sed 's#/\./#/#g')"
    while printf '%s' "$resolved" | grep -q '[^/][^/]*/\.\./'; do
      resolved="$(printf '%s' "$resolved" | sed 's#[^/][^/]*/\.\./##')"
    done

    checked=$((checked + 1))
    if [[ ! -e "$resolved" ]]; then
      echo "broken: $rel -> $href"
      broken=$((broken + 1))
    fi
  done < <(grep -o 'href="[^"]*"' "$page" | sed 's/^href="//; s/"$//')
# The rustdoc output under api/ is generated by cargo, not authored here.
done < <(find "$BOOK" -name '*.html' -not -path "$BOOK/api/*")

echo "checked $checked internal links, $broken broken"
[[ "$broken" -eq 0 ]]
